version: '3'
services:
  # backend
  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
# database
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env.db
  
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    env_file: .env.phpmyadmin
volumes:
  db_data:
